/** Wealth Discovery / EZ Wealth team roster (job titles from org chart) */
module.exports = [
  { name: 'Rahul Agarwal', jobTitle: 'Founder & CEO', order: 1 },
  { name: 'Sachin Bansal', jobTitle: 'Chief Compliance Officer (CCO)', order: 2 },
  { name: 'Manoj Rawat', jobTitle: 'Chief Operating Officer (COO)', order: 3 },
  { name: 'Mukesh Chaudhari', jobTitle: 'Chief Technology Officer (CTO)', order: 4 },
  { name: 'Subhash Upreti', jobTitle: 'Regional Head', order: 5 },
  { name: 'Satyaveer Singh', jobTitle: 'Head of Information Technology (IT)', order: 6 },
  { name: 'Pooja Kharbanda', jobTitle: 'Head of Depository Operations', order: 7 },
  { name: 'Mohit Tomar', jobTitle: 'Head of Back Office Operations', order: 8 },
  { name: 'Anuj Kumar Singh', jobTitle: 'Head of Risk Management', order: 9 },
  { name: 'Sarita Thakur', jobTitle: 'Chief Human Resources Officer (CHRO)', order: 10 },
  { name: 'Neeraj Kumar', jobTitle: 'Accounts', order: 11 },
  { name: 'Manish Kant Vats', jobTitle: 'BackOffice', order: 12 },
  { name: 'Manju Bawa', jobTitle: 'BackOffice', order: 13 },
  { name: 'Ravinder Singh', jobTitle: 'IT', order: 14 },
  { name: 'Archana Tiwari', jobTitle: 'Sales & Marketing', order: 15 },
  { name: 'Sunita Bisht', jobTitle: 'Customer Support', order: 16 },
  { name: 'Rinki Sharma', jobTitle: 'Depository', order: 17 },
  { name: 'Deepak Goel', jobTitle: 'BackOffice', order: 18 },
  { name: 'Bhupesh Malhotra', jobTitle: 'RMS', order: 19 },
  { name: 'Kailash Pandey', jobTitle: 'IT', order: 20 },
  { name: 'Piyush Dugar', jobTitle: 'Research Analyst', order: 21 },
  { name: 'Anupama Tiwari', jobTitle: 'Human Resource', order: 22 },
  { name: 'Shailendra Singh Pali', jobTitle: 'Trading Head', order: 23 },
  { name: 'Subham Kumar Sahoo', jobTitle: 'Developer', order: 24 },
  { name: 'Mukul Yadav', jobTitle: 'Developer', order: 25 },
  { name: 'Shubham Agarwal', jobTitle: 'Developer', order: 26 },
  { name: 'Abhisek Sharma', jobTitle: 'Product Manager', order: 27 },
  { name: 'Rahul Goel', jobTitle: 'AI/ML Engineer', order: 28 },
  { name: 'Nikhil Chaudhary', jobTitle: 'Full Stack Developer', order: 29 },
  { name: 'Shivangi Gupta', jobTitle: 'Full Stack Developer', order: 30 },
  { name: 'Ananya', jobTitle: 'Full Stack Mobile App Developer', order: 31 },
  { name: 'Sandeep Verma', jobTitle: 'RMS', order: 32 },
  { name: 'Geeta Singh', jobTitle: 'BackOffice', order: 33 },
  { name: 'Saurabh Khandelwal', jobTitle: 'Trading', order: 34 },
  { name: 'Prakash Karki', jobTitle: 'Trading', order: 35 },
  { name: 'Birendra Negi', jobTitle: 'Trading', order: 36 },
  { name: 'Jatin Sharma', jobTitle: 'Sales & Marketing', order: 37 },
];
